apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dp-zipkin
spec:
  replicas: 1
  selector:
   matchLabels:
    app: pod-zipkin
  template:
    metadata:
      labels:
        app: pod-zipkin
    spec:
      containers:
      - name: cont-zipkin
        image: ddas55/zipkin-distr-tracing-server
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 9411

---
apiVersion: v1
kind: Service
metadata:
  name: zipkin-collector
  labels:
    app: pod-zipkin
spec:
  selector:
    app: pod-zipkin
  type: NodePort
  ports:
  - name: http
    port: 9411
    targetPort: 9411
    nodePort: 32323
 
    
---
#apiVersion: v1
#kind: Service
#metadata:
#  labels:
#    name: zipkin
#  name: zipkin
#spec:
#  type: NodePort
#  selector:
#    app: zipkin
#  ports:
#  - name: http
#    port: 80
#    targetPort: 9411