apiVersion: v1
kind: Service
metadata:
  name: svc-grafana
#  namespace: monitoring
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 31111
  selector:
    name: grafana
  type: NodePort
  